variables:
  repository: 'jannemattila/perf-tester'

trigger:
- main
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: 'src/PerfTester/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest
